In [1]:
import pandas as pd

In [4]:
meta = pd.read_csv('/Users/pedrobassi/Downloads/UCSF_metadata_filled.csv')

/var/folders/4h/mwrzn2413d15925mbgmqnqyw0000gn/T/ipykernel_44075/4228737274.py:1: DtypeWarning: Columns (114) have mixed types. Specify dtype option on import or set low_memory=False.
  meta = pd.read_csv('/Users/pedrobassi/Downloads/UCSF_metadata_filled.csv')

In [5]:
meta

,Encrypted Accession Number,BDMAP ID,spacing,shape,sex,age,scanner,contrast,liver volume (cm^3),total liver lesion volume (cm^3),...,report,no lesion,normal pancreas,filename,Patient ID,Exam Description,Exam Completed Date,Patient Status,Pathology Confirmation,PDAC stage
0,NaN,BDMAP_00032584,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,CT ABDOMEN/PELVIS WITH CONTRAST [DATE]:37 AM_...,0,1.0,UCSF_ColonRectal_Cancer_Liver_mets_13dRFYqRCN_...,NaN,NaN,NaN,NaN,no,NaN
1,NaN,BDMAP_00032586,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,CT ABDOMEN/PELVIS WITH CONTRAST [DATE]:51 PM_...,0,1.0,UCSF_ColonRectal_Cancer_Liver_mets_2Z1Thf6qXk_...,NaN,NaN,NaN,NaN,no,NaN
2,NaN,BDMAP_00032587,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,CT ABDOMEN/PELVIS WITH CONTRAST [DATE]:38 AM_...,0,1.0,UCSF_ColonRectal_Cancer_Liver_mets_2Z1Thf6qXk_...,NaN,NaN,NaN,NaN,no,NaN
3,NaN,BDMAP_00032588,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,CT ABDOMEN/PELVIS WITH CONTRAST [DATE]:55 A...,0,0.0,UCSF_ColonRectal_Cancer_Liver_mets_3Wh6I4qx2E_...,NaN,NaN,NaN,NaN,no,NaN
4,NaN,BDMAP_00032589,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,INDICATION:_x000D_\nCT ABDOMEN/PELVIS WITH CON...,0,1.0,UCSF_ColonRectal_Cancer_Liver_mets_3iRP1PFPxv_...,NaN,NaN,NaN,NaN,no,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29160,zTohH5d,BDMAP_00086521,NaN,NaN,M,62.0,NaN,NaN,NaN,NaN,...,CT SCAN OF THE ABDOMEN AND PELVIS: [DATE].\r\n...,0,NaN,UCSF_Prediagnostic_zTohH5d_1.3.6.1.4.1.20319.1...,92462132.0,CT ABDOMEN/PELVIS WITH CONTRAST,2006-03-30 14:11:00,Inpatient,no,NaN
29161,zV9An7i,BDMAP_00086522,NaN,NaN,M,58.0,NaN,NaN,NaN,NaN,...,CT ABDOMEN: [DATE]\r\n\r\nCOMPARISON: [DATE].\...,1,NaN,UCSF_Prediagnostic_zV9An7i_1.3.6.1.4.1.20319.3...,33841728.0,CT ABDOMEN WITH CONTRAST,2008-01-22 08:55:00,Outpatient,no,NaN
29162,zfHyTsV,BDMAP_00086523,NaN,NaN,M,80.0,NaN,NaN,NaN,NaN,...,CT OF THE ABDOMEN AND PELVIS: [DATE]\r\n\r\nCO...,0,NaN,UCSF_Prediagnostic_zfHyTsV_1.3.6.1.4.1.20319.8...,62166527.0,CT ABDOMEN/PELVIS WITH CONTRAST,2007-07-03 16:37:00,Outpatient,no,NaN
29163,zqVm6qU,BDMAP_00086524,NaN,NaN,M,58.0,NaN,NaN,NaN,NaN,...,CT ABDOMEN: [DATE]\r\n\r\nCLINICAL DATA: Lung ...,1,NaN,UCSF_Prediagnostic_zqVm6qU_1.3.6.1.4.1.20319.2...,33841728.0,CT ABDOMEN WITH CONTRAST,2007-10-18 08:20:00,Outpatient,no,NaN
29164,zs0ApZl,BDMAP_00086525,NaN,NaN,F,81.0,NaN,NaN,NaN,NaN,...,CT OF THE ABDOMEN AND PELVIS: [DATE]\r\n\r\nHI...,1,NaN,UCSF_Prediagnostic_zs0ApZl_1.3.6.1.4.1.20319.3...,62226439.0,CT ABDOMEN/PELVIS WITH AND WITHOUT CONTRAST,2006-10-06 11:49:00,Outpatient,no,NaN

In [11]:
#columns with the word number of lesion
lesion_cols = [col for col in meta.columns if 'lesion instances' in col]

In [12]:
lesion_cols

['number of liver lesion instances',
 'number of pancreatic lesion instances',
 'number of kidney lesion instances',
 'number of colon lesion instances',
 'number of esophagus lesion instances',
 'number of uterus lesion instances',
 'number of spleen lesion instances',
 'number of pelvis lesion instances',
 'number of adrenal gland lesion instances',
 'number of bladder lesion instances',
 'number of gallbladder lesion instances',
 'number of breast lesion instances',
 'number of stomach lesion instances',
 'number of lung lesion instances',
 'number of bone lesion instances',
 'number of prostate lesion instances',
 'number of duodenum lesion instances']

In [13]:
#print sum for each column
for col in lesion_cols:
    print(col, meta[col].sum())

number of liver lesion instances 21845.0
number of pancreatic lesion instances 5314.0
number of kidney lesion instances 9855.0
number of colon lesion instances 1303.0
number of esophagus lesion instances 382.0
number of uterus lesion instances 1737.0
number of spleen lesion instances 3052.0
number of pelvis lesion instances 887.0
number of adrenal gland lesion instances 3055.0
number of bladder lesion instances 1403.0
number of gallbladder lesion instances 620.0
number of breast lesion instances 1508.0
number of stomach lesion instances 1179.0
number of lung lesion instances 3290.0
number of bone lesion instances 7045.0
number of prostate lesion instances 1121.0
number of duodenum lesion instances 620.0

In [15]:
chosen_tumors_new = ['colon','adrenal gland', 'esophagus', 'spleen', 'uterus', 'bladder', 'gallbladder', 'prostate', 'duodenum']

In [16]:
chosen_tumor_columns = [f'number of {tumor} lesion instances' for tumor in chosen_tumors_new]

In [21]:
#get all the rows that have any of the chosen_tumor_columns >=1 and rows where all tumors are 0
chosen_cases_pos = meta[(meta[chosen_tumor_columns].sum(axis=1) >= 1)]
chosen_cases_neg = meta[(meta[lesion_cols].sum(axis=1) == 0)]

In [23]:
chosen_cases_pos

,Encrypted Accession Number,BDMAP ID,spacing,shape,sex,age,scanner,contrast,liver volume (cm^3),total liver lesion volume (cm^3),...,report,no lesion,normal pancreas,filename,Patient ID,Exam Description,Exam Completed Date,Patient Status,Pathology Confirmation,PDAC stage
0,NaN,BDMAP_00032584,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,CT ABDOMEN/PELVIS WITH CONTRAST [DATE]:37 AM_...,0,1.0,UCSF_ColonRectal_Cancer_Liver_mets_13dRFYqRCN_...,NaN,NaN,NaN,NaN,no,NaN
3,NaN,BDMAP_00032588,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,CT ABDOMEN/PELVIS WITH CONTRAST [DATE]:55 A...,0,0.0,UCSF_ColonRectal_Cancer_Liver_mets_3Wh6I4qx2E_...,NaN,NaN,NaN,NaN,no,NaN
5,NaN,BDMAP_00032590,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,INDICATION:_x000D_\nCT ABDOMEN/PELVIS WITH CON...,0,1.0,UCSF_ColonRectal_Cancer_Liver_mets_3iRP1PFPxv_...,NaN,NaN,NaN,NaN,no,NaN
11,NaN,BDMAP_00032596,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,CT ABDOMEN/PELVIS WITH CONTRAST [DATE]:56 PM_...,0,1.0,UCSF_ColonRectal_Cancer_Liver_mets_6aIhUKsAYs_...,NaN,NaN,NaN,NaN,no,NaN
13,NaN,BDMAP_00032598,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,INDICATION:_x000D_\nCT ABDOMEN/PELVIS WITH CON...,0,1.0,UCSF_ColonRectal_Cancer_Liver_mets_7DK86ZICkY_...,NaN,NaN,NaN,NaN,no,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29154,yWXxRCi,BDMAP_00086515,NaN,NaN,F,53.0,NaN,NaN,NaN,NaN,...,CT ABDOMEN PEL W/CONTRAST [DATE]:49 PM\r\n\r\n...,0,NaN,UCSF_Prediagnostic_yWXxRCi_1.3.6.1.4.1.20319.1...,76361724.0,CT ABDOMEN/PELVIS WITH CONTRAST,2014-08-02 19:49:00,Emergency,no,NaN
29155,yaBhhZD,BDMAP_00086516,NaN,NaN,M,83.0,NaN,NaN,NaN,NaN,...,CT ABDOMEN PEL W/O CONTRAST [DATE]:[DATE] PM\r...,0,NaN,UCSF_Prediagnostic_yaBhhZD_1.3.6.1.4.1.20319.4...,22731637.0,CT ABDOMEN/PELVIS WITHOUT CONTRAST,2014-02-10 18:06:00,Emergency,no,NaN
29157,z4Ixlny,BDMAP_00086518,NaN,NaN,F,58.0,NaN,NaN,NaN,NaN,...,CONTRAST ENHANCED CT ABDOMEN AND PELVIS: [DATE...,0,NaN,UCSF_Prediagnostic_z4Ixlny_1.3.6.1.4.1.20319.1...,92427838.0,CT ABDOMEN/PELVIS WITH CONTRAST,2005-09-27 11:05:00,Outpatient,no,NaN
29159,zBGuEZy,BDMAP_00086520,NaN,NaN,M,56.0,NaN,NaN,NaN,NaN,...,CT ABDOMEN AND PELVIS WITHOUT AND WITH CONTRAS...,0,NaN,UCSF_Prediagnostic_zBGuEZy_1.3.6.1.4.1.20319.3...,98442704.0,CT ABDOMEN/PELVIS WITH AND WITHOUT CONTRAST,2007-12-13 09:16:00,Outpatient,no,NaN
29160,zTohH5d,BDMAP_00086521,NaN,NaN,M,62.0,NaN,NaN,NaN,NaN,...,CT SCAN OF THE ABDOMEN AND PELVIS: [DATE].\r\n...,0,NaN,UCSF_Prediagnostic_zTohH5d_1.3.6.1.4.1.20319.1...,92462132.0,CT ABDOMEN/PELVIS WITH CONTRAST,2006-03-30 14:11:00,Inpatient,no,NaN

In [24]:
chosen_cases_neg

,Encrypted Accession Number,BDMAP ID,spacing,shape,sex,age,scanner,contrast,liver volume (cm^3),total liver lesion volume (cm^3),...,report,no lesion,normal pancreas,filename,Patient ID,Exam Description,Exam Completed Date,Patient Status,Pathology Confirmation,PDAC stage
7,NaN,BDMAP_00032592,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,CT ABDOMEN/PELVIS WITH CONTRAST [DATE]:40 PM_...,0,1.0,UCSF_ColonRectal_Cancer_Liver_mets_4MzFFE6faD_...,NaN,NaN,NaN,NaN,no,NaN
12,NaN,BDMAP_00032597,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,INDICATION:_x000D_\nCT ABDOMEN/PELVIS WITH CON...,0,1.0,UCSF_ColonRectal_Cancer_Liver_mets_6f0Il5pAV4_...,NaN,NaN,NaN,NaN,no,NaN
61,NaN,BDMAP_00032646,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,INDICATION:_x000D_\nCT ABDOMEN/PELVIS WITH CON...,0,1.0,UCSF_ColonRectal_Cancer_Liver_mets_NXrmlW4zHY_...,NaN,NaN,NaN,NaN,no,NaN
63,NaN,BDMAP_00032648,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,INDICATION:_x000D_\nCT ABDOMEN/PELVIS WITH CON...,0,1.0,UCSF_ColonRectal_Cancer_Liver_mets_O6e786m5kN_...,NaN,NaN,NaN,NaN,no,NaN
145,NaN,BDMAP_00032734,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,CT ABDOMEN/PELVIS WITH CONTRAST [DATE]:18 PM_...,0,0.0,UCSF_ColonRectal_Cancer_Liver_mets_multiple_tp...,NaN,NaN,NaN,NaN,no,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29137,wbE6ogZ,BDMAP_00086498,NaN,NaN,M,69.0,NaN,NaN,NaN,NaN,...,CT of the abdomen and pelvis with contrast.\r\...,1,NaN,UCSF_Prediagnostic_wbE6ogZ_1.3.6.1.4.1.20319.2...,76150778.0,CT ABDOMEN/PELVIS WITH CONTRAST,2008-10-15 15:33:00,Outpatient,no,NaN
29138,wg1cQEQ,BDMAP_00086499,NaN,NaN,M,69.0,NaN,NaN,NaN,NaN,...,Procedure:CT ABDOMEN PELVIS ENHANCED\r\n\r\nDa...,1,NaN,UCSF_Prediagnostic_wg1cQEQ_1.3.6.1.4.1.20319.2...,76150778.0,CT ABDOMEN/PELVIS WITH CONTRAST,2008-10-20 17:25:00,Emergency,no,NaN
29161,zV9An7i,BDMAP_00086522,NaN,NaN,M,58.0,NaN,NaN,NaN,NaN,...,CT ABDOMEN: [DATE]\r\n\r\nCOMPARISON: [DATE].\...,1,NaN,UCSF_Prediagnostic_zV9An7i_1.3.6.1.4.1.20319.3...,33841728.0,CT ABDOMEN WITH CONTRAST,2008-01-22 08:55:00,Outpatient,no,NaN
29163,zqVm6qU,BDMAP_00086524,NaN,NaN,M,58.0,NaN,NaN,NaN,NaN,...,CT ABDOMEN: [DATE]\r\n\r\nCLINICAL DATA: Lung ...,1,NaN,UCSF_Prediagnostic_zqVm6qU_1.3.6.1.4.1.20319.2...,33841728.0,CT ABDOMEN WITH CONTRAST,2007-10-18 08:20:00,Outpatient,no,NaN
29164,zs0ApZl,BDMAP_00086525,NaN,NaN,F,81.0,NaN,NaN,NaN,NaN,...,CT OF THE ABDOMEN AND PELVIS: [DATE]\r\n\r\nHI...,1,NaN,UCSF_Prediagnostic_zs0ApZl_1.3.6.1.4.1.20319.3...,62226439.0,CT ABDOMEN/PELVIS WITH AND WITHOUT CONTRAST,2006-10-06 11:49:00,Outpatient,no,NaN

In [25]:
#mix both
chosen_cases = pd.concat([chosen_cases_pos, chosen_cases_neg])

In [28]:
# cases we can use (no unk size)
usable = pd.read_csv('/Users/pedrobassi/Downloads/UCSFLLMOutputLarge27k.csv')

/var/folders/4h/mwrzn2413d15925mbgmqnqyw0000gn/T/ipykernel_44075/3594498927.py:2: DtypeWarning: Columns (11) have mixed types. Specify dtype option on import or set low_memory=False.
  usable = pd.read_csv('/Users/pedrobassi/Downloads/UCSFLLMOutputLarge27k.csv')

In [29]:
chosen_cases = chosen_cases[chosen_cases['BDMAP ID'].isin(usable['BDMAP_ID'])]

In [30]:
chosen_cases

,Encrypted Accession Number,BDMAP ID,spacing,shape,sex,age,scanner,contrast,liver volume (cm^3),total liver lesion volume (cm^3),...,report,no lesion,normal pancreas,filename,Patient ID,Exam Description,Exam Completed Date,Patient Status,Pathology Confirmation,PDAC stage
0,NaN,BDMAP_00032584,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,CT ABDOMEN/PELVIS WITH CONTRAST [DATE]:37 AM_...,0,1.0,UCSF_ColonRectal_Cancer_Liver_mets_13dRFYqRCN_...,NaN,NaN,NaN,NaN,no,NaN
3,NaN,BDMAP_00032588,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,CT ABDOMEN/PELVIS WITH CONTRAST [DATE]:55 A...,0,0.0,UCSF_ColonRectal_Cancer_Liver_mets_3Wh6I4qx2E_...,NaN,NaN,NaN,NaN,no,NaN
5,NaN,BDMAP_00032590,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,INDICATION:_x000D_\nCT ABDOMEN/PELVIS WITH CON...,0,1.0,UCSF_ColonRectal_Cancer_Liver_mets_3iRP1PFPxv_...,NaN,NaN,NaN,NaN,no,NaN
11,NaN,BDMAP_00032596,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,CT ABDOMEN/PELVIS WITH CONTRAST [DATE]:56 PM_...,0,1.0,UCSF_ColonRectal_Cancer_Liver_mets_6aIhUKsAYs_...,NaN,NaN,NaN,NaN,no,NaN
13,NaN,BDMAP_00032598,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,INDICATION:_x000D_\nCT ABDOMEN/PELVIS WITH CON...,0,1.0,UCSF_ColonRectal_Cancer_Liver_mets_7DK86ZICkY_...,NaN,NaN,NaN,NaN,no,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28252,JuEozOeF,BDMAP_00045654,NaN,NaN,F,55.0,NaN,NaN,NaN,NaN,...,INDICATION:\r\nCT ABDOMEN/PELVIS WITH CONTRAST...,0,NaN,UCSF_JuEozOeF_1.3.6.1.4.1.20319.19187339965222...,20171999.0,CT ABDOMEN/PELVIS WITH CONTRAST,2015-07-01 11:34:00,Outpatient,no,NaN
28266,JAhT89Mi,BDMAP_00050904,NaN,NaN,F,76.0,NaN,NaN,NaN,NaN,...,INDICATION:\r\nCT ABDOMEN WITH CONTRAST [DATE...,1,NaN,UCSF_JAhT89Mi_1.3.6.1.4.1.20319.53205465469212...,28089621.0,CT ABDOMEN WITH CONTRAST,2015-07-27 12:23:00,Outpatient,no,NaN
28298,7Ruj0x2,BDMAP_00062868,NaN,NaN,M,53.0,NaN,NaN,NaN,NaN,...,CT ABDOMEN PEL W/CONTRAST [DATE]:43 PM\r\n\r\n...,1,NaN,UCSF_7Ruj0x2_1.3.6.1.4.1.20319.132291561509061...,23678910.0,CT ABDOMEN/PELVIS WITH CONTRAST,2013-02-26 13:43:00,Outpatient,no,NaN
28365,8bhgKiJV,BDMAP_00080175,NaN,NaN,M,86.0,NaN,NaN,NaN,NaN,...,INDICATION:\r\nCT ABDOMEN/PELVIS WITH CONTRAST...,1,NaN,UCSF_8bhgKiJV_1.3.6.1.4.1.20319.21294688706554...,28641645.0,CT ABDOMEN/PELVIS WITH CONTRAST,2019-10-01 11:03:00,Outpatient,no,NaN
28367,FdB2DNI,BDMAP_00081196,NaN,NaN,M,49.0,NaN,NaN,NaN,NaN,...,CT ABDOMEN/PELVIS: [DATE]\r\n\r\nCOMPARISON: C...,1,NaN,UCSF_FdB2DNI_1.3.6.1.4.1.20319.134528614711455...,91401642.0,CT ABDOMEN/PELVIS WITHOUT CONTRAST,2009-01-06 16:24:00,Emergency,no,NaN

In [31]:
#remove cases w/o BDMAP ID
chosen_cases = chosen_cases.dropna(subset=['BDMAP ID'])

In [32]:
chosen_cases

,Encrypted Accession Number,BDMAP ID,spacing,shape,sex,age,scanner,contrast,liver volume (cm^3),total liver lesion volume (cm^3),...,report,no lesion,normal pancreas,filename,Patient ID,Exam Description,Exam Completed Date,Patient Status,Pathology Confirmation,PDAC stage
0,NaN,BDMAP_00032584,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,CT ABDOMEN/PELVIS WITH CONTRAST [DATE]:37 AM_...,0,1.0,UCSF_ColonRectal_Cancer_Liver_mets_13dRFYqRCN_...,NaN,NaN,NaN,NaN,no,NaN
3,NaN,BDMAP_00032588,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,CT ABDOMEN/PELVIS WITH CONTRAST [DATE]:55 A...,0,0.0,UCSF_ColonRectal_Cancer_Liver_mets_3Wh6I4qx2E_...,NaN,NaN,NaN,NaN,no,NaN
5,NaN,BDMAP_00032590,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,INDICATION:_x000D_\nCT ABDOMEN/PELVIS WITH CON...,0,1.0,UCSF_ColonRectal_Cancer_Liver_mets_3iRP1PFPxv_...,NaN,NaN,NaN,NaN,no,NaN
11,NaN,BDMAP_00032596,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,CT ABDOMEN/PELVIS WITH CONTRAST [DATE]:56 PM_...,0,1.0,UCSF_ColonRectal_Cancer_Liver_mets_6aIhUKsAYs_...,NaN,NaN,NaN,NaN,no,NaN
13,NaN,BDMAP_00032598,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,INDICATION:_x000D_\nCT ABDOMEN/PELVIS WITH CON...,0,1.0,UCSF_ColonRectal_Cancer_Liver_mets_7DK86ZICkY_...,NaN,NaN,NaN,NaN,no,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28252,JuEozOeF,BDMAP_00045654,NaN,NaN,F,55.0,NaN,NaN,NaN,NaN,...,INDICATION:\r\nCT ABDOMEN/PELVIS WITH CONTRAST...,0,NaN,UCSF_JuEozOeF_1.3.6.1.4.1.20319.19187339965222...,20171999.0,CT ABDOMEN/PELVIS WITH CONTRAST,2015-07-01 11:34:00,Outpatient,no,NaN
28266,JAhT89Mi,BDMAP_00050904,NaN,NaN,F,76.0,NaN,NaN,NaN,NaN,...,INDICATION:\r\nCT ABDOMEN WITH CONTRAST [DATE...,1,NaN,UCSF_JAhT89Mi_1.3.6.1.4.1.20319.53205465469212...,28089621.0,CT ABDOMEN WITH CONTRAST,2015-07-27 12:23:00,Outpatient,no,NaN
28298,7Ruj0x2,BDMAP_00062868,NaN,NaN,M,53.0,NaN,NaN,NaN,NaN,...,CT ABDOMEN PEL W/CONTRAST [DATE]:43 PM\r\n\r\n...,1,NaN,UCSF_7Ruj0x2_1.3.6.1.4.1.20319.132291561509061...,23678910.0,CT ABDOMEN/PELVIS WITH CONTRAST,2013-02-26 13:43:00,Outpatient,no,NaN
28365,8bhgKiJV,BDMAP_00080175,NaN,NaN,M,86.0,NaN,NaN,NaN,NaN,...,INDICATION:\r\nCT ABDOMEN/PELVIS WITH CONTRAST...,1,NaN,UCSF_8bhgKiJV_1.3.6.1.4.1.20319.21294688706554...,28641645.0,CT ABDOMEN/PELVIS WITH CONTRAST,2019-10-01 11:03:00,Outpatient,no,NaN
28367,FdB2DNI,BDMAP_00081196,NaN,NaN,M,49.0,NaN,NaN,NaN,NaN,...,CT ABDOMEN/PELVIS: [DATE]\r\n\r\nCOMPARISON: C...,1,NaN,UCSF_FdB2DNI_1.3.6.1.4.1.20319.134528614711455...,91401642.0,CT ABDOMEN/PELVIS WITHOUT CONTRAST,2009-01-06 16:24:00,Emergency,no,NaN

In [33]:
#save to csv
chosen_cases.to_csv('/Users/pedrobassi/Downloads/UCSF_multi_tumor_colon_adrenalgland_esophagus_spleen_uterus_bladder_gallbladder_prostate_duodenum_normal.csv', index=False)

In [35]:
#remove all cases with liver, kidney or pancreas tumors
unwanted=[f'number of {tumor} lesion instances' for tumor in ['liver', 'kidney', 'pancreatic']]
chosen_cases[(chosen_cases[unwanted].sum(axis=1) == 0)]

,Encrypted Accession Number,BDMAP ID,spacing,shape,sex,age,scanner,contrast,liver volume (cm^3),total liver lesion volume (cm^3),...,report,no lesion,normal pancreas,filename,Patient ID,Exam Description,Exam Completed Date,Patient Status,Pathology Confirmation,PDAC stage
47,NaN,BDMAP_00032632,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,INDICATION:_x000D_\nCT ABDOMEN/PELVIS WITH CON...,0,1.0,UCSF_ColonRectal_Cancer_Liver_mets_HgHYNi4va9_...,NaN,NaN,NaN,NaN,no,NaN
78,NaN,BDMAP_00032664,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,CT ABDOMEN/PELVIS WITH CONTRAST [DATE]:38 P...,0,1.0,UCSF_ColonRectal_Cancer_Liver_mets_Wo8mJ7NOCZ_...,NaN,NaN,NaN,NaN,no,NaN
79,NaN,BDMAP_00032665,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,CT ABDOMEN/PELVIS WITH CONTRAST [DATE]:25 PM_...,0,1.0,UCSF_ColonRectal_Cancer_Liver_mets_XyJ7y26cbw_...,NaN,NaN,NaN,NaN,no,NaN
183,NaN,BDMAP_00032773,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,INDICATION:_x000D_\nCT ABDOMEN/PELVIS WITH CON...,0,1.0,UCSF_ColonRectal_Cancer_Liver_no_mets_08Q2DiIr...,NaN,NaN,NaN,NaN,no,NaN
184,NaN,BDMAP_00032774,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,CT ABDOMEN/PELVIS WITH CONTRAST [DATE]:47 AM_...,0,1.0,UCSF_ColonRectal_Cancer_Liver_no_mets_08uuOIR1...,NaN,NaN,NaN,NaN,no,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28252,JuEozOeF,BDMAP_00045654,NaN,NaN,F,55.0,NaN,NaN,NaN,NaN,...,INDICATION:\r\nCT ABDOMEN/PELVIS WITH CONTRAST...,0,NaN,UCSF_JuEozOeF_1.3.6.1.4.1.20319.19187339965222...,20171999.0,CT ABDOMEN/PELVIS WITH CONTRAST,2015-07-01 11:34:00,Outpatient,no,NaN
28266,JAhT89Mi,BDMAP_00050904,NaN,NaN,F,76.0,NaN,NaN,NaN,NaN,...,INDICATION:\r\nCT ABDOMEN WITH CONTRAST [DATE...,1,NaN,UCSF_JAhT89Mi_1.3.6.1.4.1.20319.53205465469212...,28089621.0,CT ABDOMEN WITH CONTRAST,2015-07-27 12:23:00,Outpatient,no,NaN
28298,7Ruj0x2,BDMAP_00062868,NaN,NaN,M,53.0,NaN,NaN,NaN,NaN,...,CT ABDOMEN PEL W/CONTRAST [DATE]:43 PM\r\n\r\n...,1,NaN,UCSF_7Ruj0x2_1.3.6.1.4.1.20319.132291561509061...,23678910.0,CT ABDOMEN/PELVIS WITH CONTRAST,2013-02-26 13:43:00,Outpatient,no,NaN
28365,8bhgKiJV,BDMAP_00080175,NaN,NaN,M,86.0,NaN,NaN,NaN,NaN,...,INDICATION:\r\nCT ABDOMEN/PELVIS WITH CONTRAST...,1,NaN,UCSF_8bhgKiJV_1.3.6.1.4.1.20319.21294688706554...,28641645.0,CT ABDOMEN/PELVIS WITH CONTRAST,2019-10-01 11:03:00,Outpatient,no,NaN
28367,FdB2DNI,BDMAP_00081196,NaN,NaN,M,49.0,NaN,NaN,NaN,NaN,...,CT ABDOMEN/PELVIS: [DATE]\r\n\r\nCOMPARISON: C...,1,NaN,UCSF_FdB2DNI_1.3.6.1.4.1.20319.134528614711455...,91401642.0,CT ABDOMEN/PELVIS WITHOUT CONTRAST,2009-01-06 16:24:00,Emergency,no,NaN